name = "jieluxia"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "jieluxiad1"
database_id = "3328100b-add6-42ec-a157-bb0e328eaaf7"

[vars]
JWT_SECRET = "change-this-in-production"
