"use client";

import {
  Activity,
  AlarmClock,
  Bell,
  BookOpen,
  Brain,
  CalendarCheck,
  CalendarDays,
  ChartNoAxesColumnIncreasing,
  CircleHelp,
  Droplet,
  Dumbbell,
  Flame,
  FlaskConical,
  Gauge,
  Gamepad2,
  Globe,
  Heart,
  Home,
  LayoutDashboard,
  Library,
  Laptop,
  LogOut,
  Medal,
  MessageCircle,
  Moon,
  Music,
  NotebookPen,
  Palette,
  PenLine,
  Pencil,
  Plane,
  Smartphone,
  Shield,
  Sparkles,
  Star,
  Target,
  Trophy,
  UserRound,
  Wallet,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  activity: Activity,
  alarm: AlarmClock,
  bell: Bell,
  book: BookOpen,
  brain: Brain,
  calendar: CalendarDays,
  chart: ChartNoAxesColumnIncreasing,
  checkin: CalendarCheck,
  community: MessageCircle,
  dashboard: LayoutDashboard,
  droplet: Droplet,
  dumbbell: Dumbbell,
  flame: Flame,
  flask: FlaskConical,
  gauge: Gauge,
  gamepad: Gamepad2,
  globe: Globe,
  help: CircleHelp,
  heart: Heart,
  home: Home,
  laptop: Laptop,
  library: Library,
  logout: LogOut,
  medal: Medal,
  message: MessageCircle,
  moon: Moon,
  music: Music,
  notebook: NotebookPen,
  palette: Palette,
  pen: PenLine,
  pencil: Pencil,
  phone: Smartphone,
  plane: Plane,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  trophy: Trophy,
  user: UserRound,
  wallet: Wallet,
  wind: Wind,
  zap: Zap,
  "🛡️": Shield,
  "💪": Dumbbell,
  "🔥": Flame,
  "⚡": Zap,
  "🌟": Sparkles,
  "🎯": Target,
  "👑": Trophy,
  "🧘": Wind,
  "🏃": Zap,
  "👤": UserRound,
};

export function AppIcon({
  name,
  size = 16,
  strokeWidth = 1.8,
}: {
  name?: string | null;
  size?: number;
  strokeWidth?: number;
}) {
  const Icon = icons[name ?? ""] ?? UserRound;
  return <Icon size={size} strokeWidth={strokeWidth} aria-hidden="true" />;
}
